const App = {
    canvas: document.getElementById("renderCanvas"),
    engine: null,
    scene: null,
    camera: null,
    terrain: null,
    sun: null,
    player: null,
    enemies: [],
    playerBullets: [],
    enemyBullets: [],
    allies: [],
    explosions: [],
    particles: [],
    villageCenters: [],
    keys: {},
    mouse: {
        x: 0,
        y: 0,
        down: false,
        aimPoint: null
    },
    arenaRadius: 120,
    score: 0,
    money: 0,
    survivalTime: 0,
    difficultyLevel: 1,
    gameOver: false,
    enemySpawnTimer: 0,
    enemySpawnDelay: 2.1,
    levelEnemiesSpawned: 0,
    levelEnemyTarget: 0,
    levelTransitionTime: 0,
    levelActive: false,
    playerShootTimer: 0,
    allyDuration: 0,
    bombFlash: 0,
    ui: {
        healthValue: document.getElementById("healthValue"),
        moneyValue: document.getElementById("moneyValue"),
        scoreValue: document.getElementById("scoreValue"),
        timeValue: document.getElementById("timeValue"),
        levelValue: document.getElementById("levelValue"),
        speedValue: document.getElementById("speedValue"),
        speedNeedleWrap: document.getElementById("speedNeedleWrap"),
        shieldButton: document.getElementById("shieldButton"),
        speedButton: document.getElementById("speedButton"),
        bombButton: document.getElementById("bombButton"),
        alliesButton: document.getElementById("alliesButton"),
        gameOverPanel: document.getElementById("gameOverPanel"),
        restartButton: document.getElementById("restartButton")
    }
};

App.engine = new BABYLON.Engine(App.canvas, true);
